<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4EC9HS4" ignored="0" name="Test" tests="4" failures="1" timestamp="2022-07-02T15:54:08 IST" time="38.223" errors="0">
  <testcase name="facebooklaunch" time="11.338" classname="com.TestNG.Assert_Concept">
    <skipped/>
  </testcase> <!-- facebooklaunch -->
  <testcase name="facebooklaunch" time="5.507" classname="com.TestNG.Assert_Concept">
    <skipped/>
  </testcase> <!-- facebooklaunch -->
  <testcase name="facebooklaunch" time="11.533" classname="com.TestNG.Assert_Concept">
    <skipped/>
  </testcase> <!-- facebooklaunch -->
  <testcase name="facebooklaunch" time="9.743" classname="com.TestNG.Assert_Concept">
    <failure type="java.lang.AssertionError" message="expected [https://www.instagram.com/accounts/login/] but found [https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjUxNzYxMDE1LCJjYWxsc2l0ZV9pZCI6MjY5NTQ4NDUzMDcyMDk1MX0%3D]">
      <![CDATA[java.lang.AssertionError: expected [https://www.instagram.com/accounts/login/] but found [https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjUxNzYxMDE1LCJjYWxsc2l0ZV9pZCI6MjY5NTQ4NDUzMDcyMDk1MX0%3D]
at com.TestNG.Assert_Concept.facebooklaunch(Assert_Concept.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- facebooklaunch -->
</testsuite> <!-- Test -->
